//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameStatistic
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnalystRec
    {
        public int ID { get; set; }
        public System.DateTime Date { get; set; }
        public string Recommendations { get; set; }
    }
}
