//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameStatistic
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sales
    {
        public int ID { get; set; }
        public int Product_ID { get; set; }
        public int Client_ID { get; set; }
        public System.DateTime Sale_date { get; set; }
    
        public virtual Clients Clients { get; set; }
        public virtual Products Products { get; set; }
    }
}
